version: '3.8'

services:
  apache:
    image: php:8.1-apache
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: apache
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - lamp 

networks:
  lamp:
    driver: bridge